name: build and test
on: 
  push:
    paths-ignore:
      - '**/README.md'
jobs:
  publish-container:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set version to env
        run: |
          echo "VERSION=$(date +'%Y.%-m.%-d.%-H%M')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            lucasgaitzsch/keycloak-theme-provider-initcontainer-keywind:latest
            lucasgaitzsch/keycloak-theme-provider-initcontainer-keywind:v${{ env.VERSION }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:v${{ env.VERSION }}
          push: true

      # - name: Docker Hub Description
      #   uses: peter-evans/dockerhub-description@v3
      #   env:
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      #     DOCKERHUB_REPOSITORY: lucasgaitzsch/keycloak-theme-provider-initcontainer-keywind
      #     short-description: ${{ github.event.repository.description }}